<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;use App\Models\{User,Category,Listing,Banner,Work,Setting};
class DatabaseSeeder extends Seeder { public function run():void{
$admin=User::create(['name'=>'Admin','email'=>'admin@shohayok.test','phone'=>'1712000000','country_code'=>'+880','city'=>'Dhaka','country'=>'Bangladesh','zip_code'=>'1205','role'=>'admin','password'=>'password','is_verified'=>true]);
$provider=User::create(['name'=>'Mohammad Ali','email'=>'provider@shohayok.test','phone'=>'1712345678','country_code'=>'+880','city'=>'Dhaka','country'=>'Bangladesh','zip_code'=>'1205','role'=>'provider','password'=>'password','is_verified'=>true]);
$user=User::create(['name'=>'Demo User','email'=>'user@shohayok.test','phone'=>'1812345678','country_code'=>'+880','city'=>'Dhaka','country'=>'Bangladesh','zip_code'=>'1207','role'=>'user','password'=>'password']);
$cats=[];foreach([['Plumber','service','🔧'],['Electrician','service','⚡'],['Carpenter','service','🪚'],['Maid','service','🧹'],['AC Repair','service','❄️'],['Computer Repair','service','💻'],['House Rent','rental','🏠'],['Car Rent','rental','🚗'],['Bike Rent','rental','🏍️'],['Office Space','rental','🏢']] as $i=>$c)$cats[]=Category::create(['name'=>$c[0],'slug'=>str($c[0])->slug(), 'type'=>$c[1],'icon'=>$c[2],'sort_order'=>$i]);
Banner::create(['title'=>'বিশ্বাসযোগ্য সেবা','subtitle'=>'আপনার হাতের মুঠোয়','button_text'=>'সেবা খুঁজুন','sort_order'=>1]);Banner::create(['title'=>'কাছাকাছি রেন্টাল','subtitle'=>'সহজে বুক করুন','button_text'=>'Rent Now','sort_order'=>2]);
foreach([['Kitchen Pipe Installation',0,'service',1500],['Electrical Wiring & Fixing',1,'service',1800],['AC Repair and Servicing',4,'service',1200],['Computer Problem Solving',5,'service',1000],['3 Bedroom Apartment',6,'rental',25000],['Toyota Axio 2018',7,'rental',2500],['Bike Rent (Yamaha FZS V3)',8,'rental',800],['Office Space (1200 sqft)',9,'rental',45000]] as $i=>$x){Listing::create(['provider_id'=>$provider->id,'category_id'=>$cats[$x[1]]->id,'type'=>$x[2],'title'=>$x[0],'slug'=>str($x[0])->slug().'-'.$i,'description'=>'Trusted and professional listing on Shohayok.','price'=>$x[3],'price_unit'=>$x[2]==='rental'?'day':'job','latitude'=>23.746,'longitude'=>90.3745,'address'=>'House-12, Road-5, Dhanmondi','city'=>'Dhaka','country'=>'Bangladesh','is_featured'=>$i<2,'is_sponsored'=>$i===2]);}
foreach([['Shakil Ahmed','Kitchen Pipe Installation','Dhanmondi, Dhaka'],['Rasel Karim','Bathroom Fitting','Uttara, Dhaka'],['Sumi Akter','Water Heater Repair','Mirpur, Dhaka']] as $w)Work::create(['provider_id'=>$provider->id,'customer_name'=>$w[0],'title'=>$w[1],'location'=>$w[2],'description'=>'Work completed successfully.','rating'=>4.8,'likes'=>24]);
foreach(['site_name'=>'Shohayok','theme_color'=>'#1268e8','language'=>'English','maintenance_mode'=>'0','maps_default_lat'=>'23.8103','maps_default_lng'=>'90.4125','provider_registration_fee'=>'1000','provider_discount_percent'=>'100','provider_bkash_number'=>'01XXXXXXXXX','provider_nagad_number'=>'01XXXXXXXXX'] as $k=>$v)Setting::updateOrCreate(['key'=>$k],['value'=>$v]);
}}
